### PR TITLE
fix: correct typos in typescript interface names

### PR DESCRIPTION
**Pull request by igophper**

### CODE REVIEW

**Comment by igophper** [comment]
"debug" 改为了 gin.DebugMode

Rrops 改为了 Props

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
"debug" changed to gin.DebugMode

Rrops changed to Props

**Comment by ssongliu** [comment]
感谢支持！

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Thanks for the support!

**Pull request merged**
