### PR TITLE
feat(ssl证书): use lego implementation of huawei cloud

### PR DESCRIPTION
**Pull request by ldez**
#### What this PR does / why we need it?

Related to #6407

It is illegal to copy the code without the license.

#### Summary of your change

Use a new version of lego.

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wanghe-fit2cloud** [comment]
感谢支持。

**Comment by wanghe-fit2cloud** [comment]
刚刚在本地构建测试包时遇到打包报错，错误内容如下：
image

**Comment by ldez** [comment]
You should update the usage of otel inside 1Panel

**Comment by ldez** [comment]
I will open a PR to fix that

**Comment by ldez** [comment]
https://github.com/1Panel-dev/1Panel/pull/6793

**Pull request merged**
