### PR TITLE
Update README for Russian language

### PR DESCRIPTION
**Pull request by JB-SelfCompany**
#### What this PR does / why we need it?
Translation is needed for Russian users.
#### Summary of your change
Translation of the README has been done. Added “Русский” button on the main page
#### Please indicate you've done the following:

- [ ] Made sure tests are passing and test coverage is added if needed.
- [ ] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wanghe-fit2cloud** [comment]
Thanks for your support!

**Comment by JB-SelfCompany** [comment]
> Thanks for your support!

I made a pull-request in the repository with the install script. 
https://github.com/1Panel-dev/installer/pull/30

:-)

**Comment by JB-SelfCompany** [comment]
Do we need to do a pull-request to the main branch with language changes?

**Comment by wanghe-fit2cloud** [comment]
> Do we need to do a pull-request to the main branch with language changes?

Not needed.

**Pull request merged**
