### PR TITLE
fix: 为了安全，使面板首页禁止搜索引擎收录

### PR DESCRIPTION
**Pull request by hhun**
#### What this PR does / why we need it?
使面板首页禁止搜索引擎收录

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by ruibaby** [comment]
https://github.com/1Panel-dev/1Panel/blob/dev/cmd/server/nginx_conf/index.html

这个我觉得也可以添加。

**Comment by hhun** [comment]
@wanghe-fit2cloud 
请问卫衣来怎么领取？
您的Github个人主页不能私信，我邮箱 2966980@qq.com

**Comment by wanghe-fit2cloud** [comment]
> @wanghe-fit2cloud 请问卫衣来怎么领取？ 您的Github个人主页不能私信，我邮箱 [2966980@qq.com](mailto:2966980@qq.com)

已私聊

**Pull request merged**
