### PR TITLE
feat: 面板配置https后，浏览器使用http协议访问自动重定向到https协议

### PR DESCRIPTION
**Pull request by bddjr**
#### What this PR does / why we need it?
[FEATURE] 面板配置https后，浏览器使用http协议访问自动重定向到https协议 #3886

#### Summary of your change
由 https://github.com/bddjr/hlfhr 接管 `ServeTLS`

#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by bddjr** [comment]
前端构建不了，我该怎么办

```powershell
PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> npm i
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm WARN deprecated @volar/html2pug@0.29.8: WARNING: This project has been renamed to @johnsoncodehk/html2pug. Install using @johnsoncodehk/html2pug instead.
npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
npm WARN deprecated vscode-pug-languageservice@0.29.8: WARNING: This project has been renamed to @volar/pug-language-service. Install using @volar/pug-language-service instead.
npm WARN deprecated @volar/vue-code-gen@0.29.8: WARNING: This project has been renamed to @vue/language-core. Install usnpm WARN deprecated vscode-typescript-languageservice@0.29.8: WARNING: This project has been renamed to @volar/typescript-language-service. Install using @volar/typescript-language-service instead.
npm WARN deprecated vscode-vue-languageservice@0.29.8: WARNING: This project has been renamed to @volar/vue-language-service. Install using @volar/vue-language-service instead.

added 999 packages, and audited 1000 packages in 2m

187 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> cnpm i
√ Installed 66 packages on D:\bddjr\Desktop\code\golang\1Panel-PR\frontend
√ All packages installed (used 29ms(network 27ms), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 0, etag hit 0 / miss 0)

PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> npm run build:dev

> 1Panel-Frontend@1.7 build:dev
> vite build --mode development

vite v2.9.18 building for development...
✓ 855 modules transformed.
transforming (870) node_modules\element-plus\es\components\button\src\use-button.mjs
✨ [vite-plugin-compression]:algorithm=gzip - compressed file successfully:


[vite:load-fallback] Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/lang/zh (imported by src/lang/modules/zh.ts): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\lang\zh'
error during build:
Error: Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/lang/zh (imported by src/lang/modules/zh.ts): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\lang\zh'
```

**Comment by ssongliu** [comment]
> 前端构建不了，我该怎么办
> 
> ```powershell
> PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> npm i
> npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
> npm WARN deprecated @volar/html2pug@0.29.8: WARNING: This project has been renamed to @johnsoncodehk/html2pug. Install using @johnsoncodehk/html2pug instead.
> npm WARN deprecated stringify-package@1.0.1: This module is not used anymore, and has been replaced by @npmcli/package-json
> npm WARN deprecated vscode-pug-languageservice@0.29.8: WARNING: This project has been renamed to @volar/pug-language-service. Install using @volar/pug-language-service instead.
> npm WARN deprecated @volar/vue-code-gen@0.29.8: WARNING: This project has been renamed to @vue/language-core. Install usnpm WARN deprecated vscode-typescript-languageservice@0.29.8: WARNING: This project has been renamed to @volar/typescript-language-service. Install using @volar/typescript-language-service instead.
> npm WARN deprecated vscode-vue-languageservice@0.29.8: WARNING: This project has been renamed to @volar/vue-language-service. Install using @volar/vue-language-service instead.
> 
> added 999 packages, and audited 1000 packages in 2m
> 
> 187 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> cnpm i
> √ Installed 66 packages on D:\bddjr\Desktop\code\golang\1Panel-PR\frontend
> √ All packages installed (used 29ms(network 27ms), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 0, etag hit 0 / miss 0)
> 
> PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> npm run build:dev
> 
> > 1Panel-Frontend@1.7 build:dev
> > vite build --mode development
> 
> vite v2.9.18 building for development...
> ✓ 855 modules transformed.
> transforming (870) node_modules\element-plus\es\components\button\src\use-button.mjs
> ✨ [vite-plugin-compression]:algorithm=gzip - compressed file successfully:
> 
> 
> [vite:load-fallback] Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/lang/zh (imported by src/lang/modules/zh.ts): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\lang\zh'
> error during build:
> Error: Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/lang/zh (imported by src/lang/modules/zh.ts): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\lang\zh'
> ```

image
 暂时得先注释一下这段

**Comment by bddjr** [comment]
还是不行，检查了下源码，似乎还有东西需要注释但是已经被依赖了

```
PS D:\bddjr\Desktop\code\golang\1Panel-PR\frontend> npm run build:dev

> 1Panel-Frontend@1.7 build:dev
> vite build --mode development

vite v2.9.18 building for development...
✓ 1870 modules transformed.

✨ [vite-plugin-compression]:algorithm=gzip - compressed file successfully:


[vite:load-fallback] Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/api/modules/setting (imported by src/layout/index.vue): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\api\modules\setting'
error during build:
Error: Could not load D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src/xpack/api/modules/setting (imported by src/layout/index.vue): ENOENT: no such file or directory, open 'D:\bddjr\Desktop\code\golang\1Panel-PR\frontend\src\xpack\api\modules\setting'
```

**Comment by bddjr** [comment]
继续移除被依赖的东西之后，前端构建好了，后端不行了，我用的go版本是 1.22.1
```
PS D:\bddjr\Desktop\code\golang\1Panel-PR> go build github.com/1Panel-dev/1Panel/cmd/server
# github.com/1Panel-dev/1Panel/backend/utils/files
backend\utils\files\fileinfo.go:87:47: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:88:61: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:89:61: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:90:44: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:272:46: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:273:43: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:274:60: undefined: syscall.Stat_t
backend\utils\files\fileinfo.go:275:60: undefined: syscall.Stat_t
# github.com/1Panel-dev/1Panel/backend/utils/terminal
backend\utils\terminal\local_cmd.go:76:11: undefined: syscall.SYS_IOCTL
backend\utils\terminal\local_cmd.go:78:11: undefined: syscall.TIOCSWINSZ
backend\utils\terminal\local_cmd.go:79:3: not enough arguments in call to syscall.Syscall
        have (unknown type, uintptr, unknown type, uintptr)
        want (uintptr, uintptr, uintptr, uintptr, uintptr)
```

**Comment by bddjr** [comment]
查了下，这东西好像要Linux才有，我有时间再试试

**Comment by bddjr** [comment]
在ubuntu20.04成功编译运行了。  

image

**Comment by wanghe-fit2cloud** [comment]
感谢您的支持。
我们建议等待 Go 官方发布更新，并按照他们的最新标准来实现这个功能。

**Comment by bddjr** [comment]
Go那边的提案issue似乎并没有取得什么进展，指望Go标准库实现似乎没啥希望

（Google公司没有这个需求）

**Comment by wanghe-fit2cloud** [comment]
了解，建议您将修改后的代码提交至 1Panel 仓库（不是引用自己的开源仓库）。

**Comment by bddjr** [comment]
🤔 但是我已经按照标准方式锁版本了啊，而且`go.sum`文件里也有校验码，不用担心我后续会改什么

您是说，我需要把那个包的源码直接塞进这个仓库里，对吗？

**Comment by wanghe-fit2cloud** [comment]
> 🤔 但是我已经按照标准方式锁版本了啊，而且`go.sum`文件里也有校验码，不用担心我后续会改什么
> 
> 您是说，我需要把那个包的源码直接塞进这个仓库里，对吗？

是的，希望您能理解 🤝。

https://www.cnblogs.com/kiwiblog/p/18106551

**Comment by bddjr** [comment]
那么我该怎么标注原仓库地址

**Comment by bddjr** [comment]
哦README已经标注了

**Pull request closed without merging**
