### PR TITLE
fix: 简化接口校验代码

### PR DESCRIPTION
**Pull request by ssongliu**

### CODE REVIEW

**Comment by trawor** [comment]
@wanghe-fit2cloud 
请问所有的 Validate 都没有给请求返回错误(比如用`helper.ErrorWithDetail`) , 而是直接 return
目前在`/api/v1/containers/compose/test`任何请求都返回 500 错误并没有提示不知道是否与这个有关? 

截屏2025-01-09 15 15 31

论坛中也有相关问题 https://bbs.fit2cloud.com/t/topic/9725

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@wanghe-fit2cloud
Please tell me that all Validates do not return errors to requests (such as using `helper.ErrorWithDetail`), but directly return
Currently, any request in `/api/v1/containers/compose/test` returns a 500 error and no prompt. I wonder if it is related to this?

Screenshot 2025-01-09 15 15 31

There are also related questions in the forum https://bbs.fit2cloud.com/t/topic/9725

**Comment by ssongliu** [comment]
这里是有正常返回的，
image

另外，如果格式错误的话，前端看起来也能正常显示
image

**Pull request merged**
