### PR TITLE
fix: Remove `proxy_cache ` from the global config to prevent it from being enabled for sites that don't need caching.

### PR DESCRIPTION
**Pull request by Anyexyz**
#### What this PR does / why we need it?
Fix the problem in https://bbs.fit2cloud.com/t/topic/8868.
#### Summary of your change
Removed `proxy_cache` from global cache configuration.
#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [x] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wanghe-fit2cloud** [comment]
感谢支持。

**Comment by zhengkunwang223** [comment]
这个配置是给反代缓存用的，去掉会出问题

**Comment by wanghe-fit2cloud** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
This configuration is used for reverse generation caching. Removing it will cause problems.

**Comment by bh1xaq** [comment]
Based on the configuration of version v1, it seems more suitable to explicitly declare `proxy_cache off` for sites where caching is not enabled.

**Pull request merged**
