### PR TITLE
Russian language support.

### PR DESCRIPTION
**Pull request by JB-SelfCompany**
#### What this PR does / why we need it?
Translation is needed for Russian users. 
#### Summary of your change
Manual translation into Russian has been made. Russian support was added to the code for correct display. 
Modified visual elements on the main screen for correct display of inscriptions in Russian. 
#### Please indicate you've done the following:

- [x] Made sure tests are passing and test coverage is added if needed.
- [x] Made sure commit message follow the rule of [Conventional Commits specification](https://www.conventionalcommits.org/).
- [ ] Considered the docs impact and opened a new docs issue or PR with docs changes if needed.

### CODE REVIEW

**Comment by wanghe-fit2cloud** [comment]
Thanks for your support!

**Comment by JB-SelfCompany** [comment]
I would really appreciate it if Russian was added to the release branch to upgrade to, and see it on a working system :)

**Comment by wanghe-fit2cloud** [comment]
> I would really appreciate it if Russian was added to the release branch to upgrade to, and see it on a working system :)

This feature is expected to be released in next month’s version.

**Comment by wanghe-fit2cloud** [comment]
@JB-SelfCompany 
- Please consider translating the README.md file into Russian and naming it /docs/README.ru.md. Thanks for your support!
- The 1Panel installation script already supports internationalization. We recommend adding Russian translations. https://github.com/1Panel-dev/installer

**Comment by JB-SelfCompany** [comment]
> @JB-SelfCompany
> 
>     * Please consider translating the README.md file into Russian and naming it /docs/README.ru.md. Thanks for your support!
> 
>     * The 1Panel installation script already supports internationalization. We recommend adding Russian translations. https://github.com/1Panel-dev/installer

OK!

**Pull request merged**
